const fs=require('fs'),path=require('path');const {chromium}=require(path.join(process.argv[3],'playwright-project/node_modules/playwright'));const html=fs.readFileSync(process.argv[2],'utf8');
(async()=>{const browser=await chromium.launch({headless:true});const records=[];for(const scenario of ['v2fly-choice','editor-draft','logout-lifetime','dispose-fallback','blob-abort','upload-release','upload-headers','start-rebootstrap','new-form-draft','finder-save-draft']){const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('http://r2-review.local/**',r=>r.fulfill({status:200,contentType:'text/html',body:html}));await page.addInitScript(()=>{window.fetch=async(url,init={})=>{if(String(url).includes('/events/stream'))return new Response(new ReadableStream({start(c){init.signal?.addEventListener('abort',()=>c.close(),{once:true})}}));return new Response(JSON.stringify(String(url).includes('/status')?{current_run:null,zapret2:{ready:true},settings:{curl_parallelism_max:10}}:{}),{headers:{'Content-Type':'application/json'}})}});await page.goto('http://r2-review.local/');const result=await page.evaluate(async scenario=>{localStorage.setItem(AUTH_TOKEN_KEY,'review');await startAuthenticatedUi();stopRealtimeFallback();const normal=window.fetch;
 if(scenario==='finder-save-draft'){state.customPresets.finder['old-list']=['youtube.com'];state.customPresetMeta.finder['old-list']={total_count:1,enabled_count:1};el('finder-preset-select').innerHTML='<option value="custom">manual</option><option value="custom:old-list">old</option>';el('finder-preset-select').value='custom:old-list';el('finder-domains').value='youtube.com';let release;window.fetch=(url,init)=>String(url).includes('/presets/save')?new Promise(r=>release=r):normal(url,init);const pending=savePreset('finder');await new Promise(r=>setTimeout(r,0));el('finder-domains').value='discord.com';el('finder-domains').dispatchEvent(new Event('input',{bubbles:true}));const expected={select:el('finder-preset-select').value,domains:el('finder-domains').value};release(new Response(JSON.stringify({})));await pending;return {expected,actual:{select:el('finder-preset-select').value,domains:el('finder-domains').value}};}
 if(scenario==='new-form-draft'){el('preset-new-name').value='old-list';el('preset-new-domains').value='youtube.com';let release;window.fetch=(url,init)=>String(url).includes('/presets/save')?new Promise(r=>release=r):normal(url,init);const pending=savePresetNew();await new Promise(r=>setTimeout(r,0));el('preset-new-name').value='next-list';el('preset-new-name').dispatchEvent(new Event('input',{bubbles:true}));el('preset-new-domains').value='discord.com';el('preset-new-domains').dispatchEvent(new Event('input',{bubbles:true}));release(new Response(JSON.stringify({})));await pending;return {expected:{name:'next-list',domains:'discord.com'},actual:{name:el('preset-new-name').value,domains:el('preset-new-domains').value}};}
 if(scenario==='upload-headers'){const transfer=new DataTransfer();transfer.items.add(new File(['zip'],'review.zip'));el('backup-upload-file').files=transfer.files;let response,release;window.fetch=(url,init)=>String(url).includes('/backups/upload')?new Promise(r=>{release=()=>r(response={ok:true,status:200,json:async()=>({})})}):normal(url,init);const pending=uploadBackup();await new Promise(r=>setTimeout(r,0));release();uiControllers.backups.dispose();await pending;return {retainsApiRequestLifetime:!!response.__gpRequestLifetime};}
 if(scenario==='start-rebootstrap'){el('finder-domains').value='youtube.com';window.fetch=(url,init)=>String(url).includes('/run-settings/save')?new Promise((resolve,reject)=>{init.signal.addEventListener('abort',()=>reject(new DOMException('cancelled','AbortError')),{once:true})}):normal(url,init);document.querySelector('button[data-action="run-selected-discovery"]').click();await new Promise(r=>setTimeout(r,0));await startAuthenticatedUi();await new Promise(r=>setTimeout(r,15));return {shellPresent:!!el('app-shell'),sessionState:sessionController.state()};}
 if(scenario==='v2fly-choice'){state.v2flyCategories={categories:['old','new']};el('v2fly-preset-name').value='v2fly-old';el('v2fly-category-search').value='old';let release;window.fetch=(url,init)=>String(url).includes('/category-domains')?new Promise(r=>release=r):normal(url,init);const pending=previewV2flyPreset();await new Promise(r=>setTimeout(r,0));el('v2fly-category-search').value='new';el('v2fly-category-search').dispatchEvent(new Event('input',{bubbles:true}));release(new Response(JSON.stringify({domains:['youtube.com']})));await pending;return {category:el('v2fly-category-search').value,name:el('v2fly-preset-name').value,domains:el('v2fly-domains').value,preview:state.v2flyPreview};}
 if(scenario==='editor-draft'){state.customPresets={finder:{},common:{}};state.customPresetMeta={finder:{old:{total_count:1,enabled_count:1}},common:{}};state.presetManager.name='old';el('preset-manager-name').innerHTML='<option value="old">old</option>';let release;window.fetch=(url,init)=>String(url).includes('/presets/domains')?new Promise(r=>release=r):normal(url,init);const pending=loadPresetEditorFromSelection({silent:true});await new Promise(r=>setTimeout(r,0));el('preset-editor-domains').value='discord.com';el('preset-editor-domains').dispatchEvent(new Event('input',{bubbles:true}));release(new Response(JSON.stringify({domains:[{domain:'youtube.com'}],has_more:false})));await pending;return {expectedDraft:'discord.com',actualDraft:el('preset-editor-domains').value};}
 if(scenario==='logout-lifetime'){let signal;window.fetch=(url,init)=>String(url).includes('/releases/available')?new Promise((resolve,reject)=>{signal=init.signal;init.signal.addEventListener('abort',()=>reject(new DOMException('cancelled','AbortError')),{once:true})}):normal(url,init);const pending=checkReleases();await new Promise(r=>setTimeout(r,0));logout();let rejection;try{await pending}catch(e){rejection=e.message}return {signalAborted:signal.aborted,rejection,shellPresent:!!el('app-shell')};}
 if(scenario==='dispose-fallback'){realtimeController.start();await new Promise(r=>setTimeout(r,0));disposeApplication();return {fallbackTimer:realtimeController._fallbackTimer,disposed:realtimeController._disposed,streamController:!!realtimeController._controller};}
 if(scenario==='blob-abort'){let signal,release;window.fetch=(url,init)=>String(url).includes('download-archive')?new Promise(r=>{signal=init.signal;release=r}):normal(url,init);const pending=downloadBackup('/api/core/backups/download-archive?snapshot_id=review','review');await new Promise(r=>setTimeout(r,0));uiControllers.backups.dispose();const aborted=signal.aborted;release(new Response('zip'));await pending;return {requestAbortedByOwnerDispose:aborted};}
 if(scenario==='upload-release'){const transfer=new DataTransfer();transfer.items.add(new File(['zip'],'review.zip',{type:'application/zip'}));el('backup-upload-file').files=transfer.files;let response,release;window.fetch=(url,init)=>String(url).includes('/backups/upload')?Promise.resolve(response={ok:true,status:200,json:()=>new Promise(r=>release=r)}):normal(url,init);const pending=uploadBackup();await new Promise(r=>setTimeout(r,0));uiControllers.backups.dispose();release({});await pending;return {retainsApiRequestLifetime:!!response.__gpRequestLifetime};}
},scenario);await page.waitForTimeout(30);records.push({scenario,result,errors});await page.close();}await browser.close();for(const row of records){
  if(row.errors.length)throw Error(row.scenario+': page errors '+row.errors.join(';'));
  const r=row.result;
  const pass={
    'v2fly-choice':()=>r.category==='new' && r.name==='v2fly-new' && r.domains==='' && r.preview===null,
    'editor-draft':()=>r.actualDraft===r.expectedDraft,
    'logout-lifetime':()=>r.signalAborted && !r.rejection && !r.shellPresent,
    'dispose-fallback':()=>!r.fallbackTimer && r.disposed && !r.streamController,
    'blob-abort':()=>r.requestAbortedByOwnerDispose,
    'upload-release':()=>!r.retainsApiRequestLifetime,
    'upload-headers':()=>!r.retainsApiRequestLifetime,
    'new-form-draft':()=>JSON.stringify(r.actual)===JSON.stringify(r.expected),
    'finder-save-draft':()=>JSON.stringify(r.actual)===JSON.stringify(r.expected),
    'start-rebootstrap':()=>r.shellPresent && r.sessionState==='ready',
  }[row.scenario]();
  if(!pass)throw Error(row.scenario+': '+JSON.stringify(r));
}console.log(JSON.stringify({pass:true,scenarios:records}));})().catch(e=>{console.error(e.stack);process.exitCode=1});
